name: BuildWindows

on:
  push:
    branches: ["master"]
  workflow_dispatch:

jobs:
  buildWindows:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: 3.41.6
          channel: stable
          cache: true

      - name: Enable Windows desktop
        run: flutter config --enable-windows-desktop

      - name: Get dependencies
        run: flutter pub get

      - name: Build Flutter Windows release
        run: flutter build windows --release

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: WindowsApp
          path: build/windows/x64/runner/Release/
          retention-days: 30
