name: BuildMacos

on:
  push:
    branches: ["master"]
  workflow_dispatch:

jobs:
  buildMacOS:
    runs-on: macos-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: 3.41.6
          channel: stable
          cache: true

      - name: Enable macOS desktop
        run: flutter config --enable-macos-desktop

      - name: Get dependencies
        run: flutter pub get

      - name: Build Flutter macOS release
        run: |
          flutter build macos --release
          cd build/macos/Build/Products/Release
          zip -r get_file_name_assistant.app.zip get_file_name_assistant.app
          ls -la

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: MacosApp
          path: build/macos/Build/Products/Release/get_file_name_assistant.app.zip
          retention-days: 30
